# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delight', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delighttag',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='delight',
            name='author',
        ),
        migrations.RemoveField(
            model_name='delight',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='delight',
            name='img_url',
        ),
        migrations.AlterField(
            model_name='delight',
            name='content',
            field=models.CharField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='DelightTag',
        ),
    ]
