# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delight', '0002_auto_20170810_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delight',
            name='title',
        ),
        migrations.AlterField(
            model_name='delight',
            name='number',
            field=models.CharField(default='#001', max_length=10),
        ),
    ]
