# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delight', '0003_auto_20170810_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='delight',
            name='img_url',
            field=models.CharField(default='#', max_length=1000),
        ),
    ]
