# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delight', '0004_delight_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='delight',
            name='img_alt_tag',
            field=models.CharField(default='Plastic Packaging', max_length=500),
        ),
    ]
