# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 08:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delight', '0005_delight_img_alt_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='delight',
            name='author',
            field=models.CharField(default='Adurcup', max_length=100),
        ),
        migrations.AddField(
            model_name='delight',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 6, 14, 2, 41, 382839), editable=False),
        ),
        migrations.AddField(
            model_name='delight',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 6, 14, 2, 41, 382895), editable=False),
        ),
    ]
