# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=models.CharField(default='#', max_length=500),
        ),
    ]
