# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170810_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='summary',
            field=models.CharField(default='#', max_length=500),
        ),
    ]
