# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170810_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='summary',
            field=models.TextField(default='#'),
        ),
    ]
