# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170812_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img_url',
            field=models.CharField(default='#', max_length=1000),
        ),
    ]
