# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_unsubscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='unsubscribe',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
