# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 08:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsmail', '0005_newsmail_img_alt_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmail',
            name='created_at',
        ),
        migrations.AddField(
            model_name='newsmail',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 6, 14, 5, 37, 82744), editable=False),
        ),
        migrations.AddField(
            model_name='newsmail',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 6, 14, 5, 37, 82777), editable=False),
        ),
    ]
