# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default='#', max_length=500),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_watch_url',
            field=models.CharField(default='#', max_length=1000),
        ),
    ]
