# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 08:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20170812_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 6, 14, 15, 53, 157352), editable=False),
        ),
        migrations.AddField(
            model_name='video',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 6, 14, 15, 53, 157422), editable=False),
        ),
    ]
